### ISSUE TITLE
Nodejs 7.1 warning

### ISSUE THREAD

**Issue by horosgrisa** [MikeKovarik/gulp-better-rollup#1]
I use Nodejs 7.1, and I obtain following error
```
DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```

**Comment by MikeKovarik** [comment]
This is odd. By quickly looking at the code i couldn't spot anything that could be causing it. Maybe it's caused by some of the dependency. Unfortunately I can't take a deeper look now, because of my other project and prolonged illness. I'd like to solve it but until then PRs are welcomed
