### ISSUE TITLE
How to import from node modules?

### ISSUE THREAD

**Issue by Craeckerffm** [MikeKovarik/gulp-better-rollup#10]
i have 

var rollup = require('gulp-better-rollup')
var babel = require('rollup-plugin-babel')
var resolve = require('rollup-plugin-node-resolve')

gulp.task('js', () => {
  gulp.src(config.src.js)
    .pipe(sourcemaps.init())
    .pipe(rollup({
      plugins: [resolve(), babel({
      	exclude: 'node_modules/**'
      })]
    }, {
      format: 'cjs',
    }))
    .pipe(sourcemaps.write())
    .pipe(gulp.dest(config.dest.js))

But with every try im getting: 

node_modules/**/*.js The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten 
....
Non-existent export 'default' is imported from node_modules/**/*.js

**Comment by FinesseRus** [comment]
Do your options work with [a pure rollup](https://github.com/rollup/rollup/wiki/JavaScript-API)?

**Comment by BennieCopeland** [comment]
Getting the same issue.

rollup-config.js
``` JavaScript
import noderesolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'
import uglify from 'rollup-plugin-uglify'

export default {
    entry: 'src/main.js',
    dest: 'build/js/app.js',
    sourceMap: false,
    format: 'iife',
    onwarn: function (warning) {
        if (warning.code === 'THIS_IS_UNDEFINED') { return; }
        console.warn(warning.message);
    },
    plugins: [
        noderesolve({ jsnext: true, module: true }),
        commonjs({
            include: 'node_modules/rxjs/**'
        }),
        uglify()
    ]
}
```

gulp task
``` JavaScript
    var rollupOptions = {
        format: 'iife',
        onwarn: function (warning) {
            if (warning.code === 'THIS_IS_UNDEFINED') { return; }
            console.warn(warning.message);
        },
        plugins: [
            noderesolve({ jsnext: true, module: true }),
            commonjs({
                include: 'node_modules/rxjs/**'
            }),
            uglify()
        ]
    }

    return gulp.src( 'src/main.js' )
        .pipe( rollup( rollupOptions ) )
        .pipe( rename( 'app.js' ) )
        .pipe( gulp.dest( buildDirectory + '/js' ) );
```

I receive a whole bunch of `'@angular/platform-browser' is imported by src\main.js, but could not be resolved – treating it as an external dependency` errors.

**Comment by ProLoser** [comment]
This package's dependency on rollup locks you in to rollup v0.x instead of v3.2+ which has this functionality fixed. @MikeKovarik either bump up the rollup dependency version or maybe make it a peer dep?

**Comment by matthewblewitt** [comment]
Getting the same issue

**Comment by bewards** [comment]
Was there ever a solution to this?
