### ISSUE TITLE
This plugin does the same thing the original gulp-rollup was blacklisted for.

### ISSUE THREAD

**Issue by Permutatrix** [MikeKovarik/gulp-better-rollup#2]
It reads from the filesystem directly, using `gulp.src` as a globber. [Have a look here.](https://github.com/mcasimir/gulp-rollup/pull/16#issuecomment-156866698)

**Comment by MikeKovarik** [comment]
https://github.com/gulpjs/plugins/pull/221#issuecomment-264660596
