### ISSUE TITLE
Possible to include the newest version of rollup directly?

### ISSUE THREAD

**Issue by bridgeport** [MikeKovarik/gulp-better-rollup#22]
Thanks for this great package. Would you consider the possibility to **optionally** allow including or injecting rollup directly into gulp-better-rollup so that the newest or different rollup versions can be used with this plugin?

Something such as:

```javascript
const actualRollup = require('rollup');
const betterRollup = require('gulp-better-rollup');

gulp.task('lib-build', () => {
  gulp.src('lib/index.js')
    .pipe(betterRollup({
      injectRollup: actualRollup,
      plugins: [babel()]
    }))
    .pipe(gulp.dest('dist'))
})
```

Thanks.

**Comment by MikeKovarik** [comment]
Yes, I must've forgot to document it but it is possible to supply your own rollup version with `rollup` property (a little simpler than your proposed `injectRollup`)

``` js
const betterRollup = require('gulp-better-rollup');
...
    .pipe(betterRollup({
      rollup: require('rollup')
    }))
```
