### ISSUE TITLE
npm publish to update dependencies

### ISSUE THREAD

**Issue by yongtw123** [MikeKovarik/gulp-better-rollup#33]
Some rollup plugins such as uglify requires rollup version 0.66 and up, and although gulp-better-rollup did update the dependency, the change has yet been published to npm. May I inquire if it's possible to bump the version and publish again? Thanks for the consideration.

**Comment by MikeKovarik** [comment]
Yes of course, thought the cadence of rollup makes it hard for me to keep up. For the cases of non breaking updates in rollup there's an option to inject custom rollup version with the `rollup` property.

```js
const betterRollup = require('gulp-better-rollup');

gulp.task('lib-build', () => {
  gulp.src('lib/index.js')
    .pipe(betterRollup({
      rollup: require('rollup')
      plugins: [babel()],
      format: 'cjs',
      ...
    }))
})
```
