### ISSUE TITLE
move rollup to peerDependencies

### ISSUE THREAD

**Issue by NewFuture** [MikeKovarik/gulp-better-rollup#41]
related #40 

Just like the `gulp-typescript`  dependents on `typescript`.

It's better to set Rollup as  a peerDependency

**Comment by Finesse** [comment]
What problem does it solve?

@MikeKovarik As Rollup is a peer dependency, the installation command in the readme should be changed from

```bash
npm install gulp-better-rollup --save-dev
```
to
```bash
npm install gulp-better-rollup rollup@^1 --save-dev
```

**Comment by MikeKovarik** [comment]
People kept having issues about us including old version of rollup and/or being unable to include their own. I't seems fine to let them install their own version. Good catch about the readme though. I'm also thinking about adding some warning to the code

**Comment by Finesse** [comment]
I think it's not an issue since Rollup got the stable v1 release because there won't be so many major versions.

I don't think the peer dependency approach is bad, I just wonder why it is used.

**Comment by MikeKovarik** [comment]
Honestly. Because greenkeeper buzzing me about every single minor or bugfix is effing annoying :D.

**Comment by NewFuture** [comment]
I think that `gulp-better-rollup` is an adaptor for `rollup`，

What this plugin does, is to tell the `rollup`  how to handle files with parameters.
And, Which version to use, is decided by the current user or environment.

For example, there may be some changes between version A and version B of rollup. 
The output is a little different, but the API is the same.
`gulp-better-rollup`  needs to do nothing about those.
Users can decide to choose different versions by installing different rollup dependencies (not always the latest one), instead of upgrade/downgrade this plugin.
